// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: t2.proto

package t2

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateT2Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Deprecated: Do not use.
	F1 string `protobuf:"bytes,1,opt,name=f1,proto3" json:"f1,omitempty"`
}

func (x *CreateT2Req) Reset() {
	*x = CreateT2Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_t2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateT2Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateT2Req) ProtoMessage() {}

func (x *CreateT2Req) ProtoReflect() protoreflect.Message {
	mi := &file_t2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateT2Req.ProtoReflect.Descriptor instead.
func (*CreateT2Req) Descriptor() ([]byte, []int) {
	return file_t2_proto_rawDescGZIP(), []int{0}
}

// Deprecated: Do not use.
func (x *CreateT2Req) GetF1() string {
	if x != nil {
		return x.F1
	}
	return ""
}

type CreateT2Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateT2Rsp) Reset() {
	*x = CreateT2Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_t2_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateT2Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateT2Rsp) ProtoMessage() {}

func (x *CreateT2Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_t2_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateT2Rsp.ProtoReflect.Descriptor instead.
func (*CreateT2Rsp) Descriptor() ([]byte, []int) {
	return file_t2_proto_rawDescGZIP(), []int{1}
}

type UpdateT2Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateT2Req) Reset() {
	*x = UpdateT2Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_t2_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateT2Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateT2Req) ProtoMessage() {}

func (x *UpdateT2Req) ProtoReflect() protoreflect.Message {
	mi := &file_t2_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateT2Req.ProtoReflect.Descriptor instead.
func (*UpdateT2Req) Descriptor() ([]byte, []int) {
	return file_t2_proto_rawDescGZIP(), []int{2}
}

type UpdateT2Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateT2Rsp) Reset() {
	*x = UpdateT2Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_t2_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateT2Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateT2Rsp) ProtoMessage() {}

func (x *UpdateT2Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_t2_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateT2Rsp.ProtoReflect.Descriptor instead.
func (*UpdateT2Rsp) Descriptor() ([]byte, []int) {
	return file_t2_proto_rawDescGZIP(), []int{3}
}

type DeleteT2Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteT2Req) Reset() {
	*x = DeleteT2Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_t2_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteT2Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteT2Req) ProtoMessage() {}

func (x *DeleteT2Req) ProtoReflect() protoreflect.Message {
	mi := &file_t2_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteT2Req.ProtoReflect.Descriptor instead.
func (*DeleteT2Req) Descriptor() ([]byte, []int) {
	return file_t2_proto_rawDescGZIP(), []int{4}
}

type DeleteT2Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteT2Rsp) Reset() {
	*x = DeleteT2Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_t2_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteT2Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteT2Rsp) ProtoMessage() {}

func (x *DeleteT2Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_t2_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteT2Rsp.ProtoReflect.Descriptor instead.
func (*DeleteT2Rsp) Descriptor() ([]byte, []int) {
	return file_t2_proto_rawDescGZIP(), []int{5}
}

type GetT2Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetT2Req) Reset() {
	*x = GetT2Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_t2_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetT2Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetT2Req) ProtoMessage() {}

func (x *GetT2Req) ProtoReflect() protoreflect.Message {
	mi := &file_t2_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetT2Req.ProtoReflect.Descriptor instead.
func (*GetT2Req) Descriptor() ([]byte, []int) {
	return file_t2_proto_rawDescGZIP(), []int{6}
}

type GetT2Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetT2Rsp) Reset() {
	*x = GetT2Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_t2_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetT2Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetT2Rsp) ProtoMessage() {}

func (x *GetT2Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_t2_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetT2Rsp.ProtoReflect.Descriptor instead.
func (*GetT2Rsp) Descriptor() ([]byte, []int) {
	return file_t2_proto_rawDescGZIP(), []int{7}
}

type ListT2Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListT2Req) Reset() {
	*x = ListT2Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_t2_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListT2Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListT2Req) ProtoMessage() {}

func (x *ListT2Req) ProtoReflect() protoreflect.Message {
	mi := &file_t2_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListT2Req.ProtoReflect.Descriptor instead.
func (*ListT2Req) Descriptor() ([]byte, []int) {
	return file_t2_proto_rawDescGZIP(), []int{8}
}

type ListT2Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListT2Rsp) Reset() {
	*x = ListT2Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_t2_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListT2Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListT2Rsp) ProtoMessage() {}

func (x *ListT2Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_t2_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListT2Rsp.ProtoReflect.Descriptor instead.
func (*ListT2Rsp) Descriptor() ([]byte, []int) {
	return file_t2_proto_rawDescGZIP(), []int{9}
}

type Person struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    uint64           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email string           `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name  string           `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Home  *Person_Location `protobuf:"bytes,4,opt,name=home,proto3" json:"home,omitempty"`
}

func (x *Person) Reset() {
	*x = Person{}
	if protoimpl.UnsafeEnabled {
		mi := &file_t2_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_t2_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_t2_proto_rawDescGZIP(), []int{10}
}

func (x *Person) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Person) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Person) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Person) GetHome() *Person_Location {
	if x != nil {
		return x.Home
	}
	return nil
}

type Person_Location struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lat float64 `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng float64 `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
}

func (x *Person_Location) Reset() {
	*x = Person_Location{}
	if protoimpl.UnsafeEnabled {
		mi := &file_t2_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Person_Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person_Location) ProtoMessage() {}

func (x *Person_Location) ProtoReflect() protoreflect.Message {
	mi := &file_t2_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person_Location.ProtoReflect.Descriptor instead.
func (*Person_Location) Descriptor() ([]byte, []int) {
	return file_t2_proto_rawDescGZIP(), []int{10, 0}
}

func (x *Person_Location) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Person_Location) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

var File_t2_proto protoreflect.FileDescriptor

var file_t2_proto_rawDesc = []byte{
	0x0a, 0x08, 0x74, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x74, 0x32, 0x1a, 0x1c,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x29, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x32, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x02, 0x66, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x0a, 0x18, 0x01, 0xfa, 0x42, 0x05, 0x72, 0x03, 0xa8, 0x01, 0x01, 0x52, 0x02, 0x66, 0x31,
	0x22, 0x0d, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x32, 0x52, 0x73, 0x70, 0x22,
	0x0d, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x32, 0x52, 0x65, 0x71, 0x22, 0x0d,
	0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x32, 0x52, 0x73, 0x70, 0x22, 0x0d, 0x0a,
	0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x32, 0x52, 0x65, 0x71, 0x22, 0x0d, 0x0a, 0x0b,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x32, 0x52, 0x73, 0x70, 0x22, 0x0a, 0x0a, 0x08, 0x47,
	0x65, 0x74, 0x54, 0x32, 0x52, 0x65, 0x71, 0x22, 0x0a, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x54, 0x32,
	0x52, 0x73, 0x70, 0x22, 0x0b, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x32, 0x52, 0x65, 0x71,
	0x22, 0x0b, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x32, 0x52, 0x73, 0x70, 0x22, 0x9a, 0x02,
	0x0a, 0x06, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x32, 0x03, 0x20, 0xe7, 0x07, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1d, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x60, 0x01, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x12, 0x42, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x2e, 0xfa, 0x42, 0x2b, 0x72, 0x29, 0x28, 0x80, 0x02, 0x32, 0x24, 0x5e, 0x5b, 0x5e, 0x5b, 0x30,
	0x2d, 0x39, 0x5d, 0x41, 0x2d, 0x5a, 0x61, 0x2d, 0x7a, 0x5d, 0x2b, 0x28, 0x20, 0x5b, 0x5e, 0x5b,
	0x30, 0x2d, 0x39, 0x5d, 0x41, 0x2d, 0x5a, 0x61, 0x2d, 0x7a, 0x5d, 0x2b, 0x29, 0x2a, 0x24, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x31, 0x0a, 0x04, 0x68, 0x6f, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74, 0x32, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x2e,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x8a, 0x01, 0x02,
	0x10, 0x01, 0x52, 0x04, 0x68, 0x6f, 0x6d, 0x65, 0x1a, 0x60, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x01, 0x42, 0x17, 0xfa, 0x42, 0x14, 0x12, 0x12, 0x19, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x56,
	0x40, 0x29, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x56, 0xc0, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x12,
	0x29, 0x0a, 0x03, 0x6c, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x42, 0x17, 0xfa, 0x42,
	0x14, 0x12, 0x12, 0x19, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x66, 0x40, 0x29, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x80, 0x66, 0xc0, 0x52, 0x03, 0x6c, 0x6e, 0x67, 0x32, 0xdf, 0x01, 0x0a, 0x02, 0x54,
	0x32, 0x12, 0x2e, 0x0a, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x32, 0x12, 0x0f, 0x2e,
	0x74, 0x32, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x32, 0x52, 0x65, 0x71, 0x1a, 0x0f,
	0x2e, 0x74, 0x32, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x32, 0x52, 0x73, 0x70, 0x22,
	0x00, 0x12, 0x2c, 0x0a, 0x08, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x32, 0x12, 0x0f, 0x2e,
	0x74, 0x32, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x32, 0x52, 0x65, 0x71, 0x1a, 0x0f,
	0x2e, 0x74, 0x32, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x32, 0x52, 0x73, 0x70, 0x12,
	0x2c, 0x0a, 0x08, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x32, 0x12, 0x0f, 0x2e, 0x74, 0x32,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x32, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x74,
	0x32, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x32, 0x52, 0x73, 0x70, 0x12, 0x25, 0x0a,
	0x05, 0x47, 0x65, 0x74, 0x54, 0x32, 0x12, 0x0c, 0x2e, 0x74, 0x32, 0x2e, 0x47, 0x65, 0x74, 0x54,
	0x32, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x74, 0x32, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x32, 0x52,
	0x73, 0x70, 0x22, 0x00, 0x12, 0x26, 0x0a, 0x06, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x32, 0x12, 0x0d,
	0x2e, 0x74, 0x32, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x32, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e,
	0x74, 0x32, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x32, 0x52, 0x73, 0x70, 0x42, 0x23, 0x0a, 0x02,
	0x74, 0x32, 0x50, 0x01, 0x5a, 0x1b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x66, 0x65, 0x6e, 0x67, 0x6c, 0x65, 0x6e, 0x67, 0x2f, 0x64, 0x64, 0x64, 0x64, 0x2f, 0x74,
	0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_t2_proto_rawDescOnce sync.Once
	file_t2_proto_rawDescData = file_t2_proto_rawDesc
)

func file_t2_proto_rawDescGZIP() []byte {
	file_t2_proto_rawDescOnce.Do(func() {
		file_t2_proto_rawDescData = protoimpl.X.CompressGZIP(file_t2_proto_rawDescData)
	})
	return file_t2_proto_rawDescData
}

var file_t2_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_t2_proto_goTypes = []interface{}{
	(*CreateT2Req)(nil),     // 0: t2.CreateT2Req
	(*CreateT2Rsp)(nil),     // 1: t2.CreateT2Rsp
	(*UpdateT2Req)(nil),     // 2: t2.UpdateT2Req
	(*UpdateT2Rsp)(nil),     // 3: t2.UpdateT2Rsp
	(*DeleteT2Req)(nil),     // 4: t2.DeleteT2Req
	(*DeleteT2Rsp)(nil),     // 5: t2.DeleteT2Rsp
	(*GetT2Req)(nil),        // 6: t2.GetT2Req
	(*GetT2Rsp)(nil),        // 7: t2.GetT2Rsp
	(*ListT2Req)(nil),       // 8: t2.ListT2Req
	(*ListT2Rsp)(nil),       // 9: t2.ListT2Rsp
	(*Person)(nil),          // 10: t2.Person
	(*Person_Location)(nil), // 11: t2.Person.Location
}
var file_t2_proto_depIdxs = []int32{
	11, // 0: t2.Person.home:type_name -> t2.Person.Location
	0,  // 1: t2.T2.CreateT2:input_type -> t2.CreateT2Req
	2,  // 2: t2.T2.UpdateT2:input_type -> t2.UpdateT2Req
	4,  // 3: t2.T2.DeleteT2:input_type -> t2.DeleteT2Req
	6,  // 4: t2.T2.GetT2:input_type -> t2.GetT2Req
	8,  // 5: t2.T2.ListT2:input_type -> t2.ListT2Req
	1,  // 6: t2.T2.CreateT2:output_type -> t2.CreateT2Rsp
	3,  // 7: t2.T2.UpdateT2:output_type -> t2.UpdateT2Rsp
	5,  // 8: t2.T2.DeleteT2:output_type -> t2.DeleteT2Rsp
	7,  // 9: t2.T2.GetT2:output_type -> t2.GetT2Rsp
	9,  // 10: t2.T2.ListT2:output_type -> t2.ListT2Rsp
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_t2_proto_init() }
func file_t2_proto_init() {
	if File_t2_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_t2_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateT2Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_t2_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateT2Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_t2_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateT2Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_t2_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateT2Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_t2_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteT2Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_t2_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteT2Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_t2_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetT2Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_t2_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetT2Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_t2_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListT2Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_t2_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListT2Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_t2_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Person); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_t2_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Person_Location); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_t2_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_t2_proto_goTypes,
		DependencyIndexes: file_t2_proto_depIdxs,
		MessageInfos:      file_t2_proto_msgTypes,
	}.Build()
	File_t2_proto = out.File
	file_t2_proto_rawDesc = nil
	file_t2_proto_goTypes = nil
	file_t2_proto_depIdxs = nil
}
