// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: t2.proto

package t2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateT2Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateT2Req) Reset() {
	*x = CreateT2Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_t2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateT2Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateT2Req) ProtoMessage() {}

func (x *CreateT2Req) ProtoReflect() protoreflect.Message {
	mi := &file_t2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateT2Req.ProtoReflect.Descriptor instead.
func (*CreateT2Req) Descriptor() ([]byte, []int) {
	return file_t2_proto_rawDescGZIP(), []int{0}
}

type CreateT2Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateT2Rsp) Reset() {
	*x = CreateT2Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_t2_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateT2Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateT2Rsp) ProtoMessage() {}

func (x *CreateT2Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_t2_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateT2Rsp.ProtoReflect.Descriptor instead.
func (*CreateT2Rsp) Descriptor() ([]byte, []int) {
	return file_t2_proto_rawDescGZIP(), []int{1}
}

type UpdateT2Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateT2Req) Reset() {
	*x = UpdateT2Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_t2_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateT2Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateT2Req) ProtoMessage() {}

func (x *UpdateT2Req) ProtoReflect() protoreflect.Message {
	mi := &file_t2_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateT2Req.ProtoReflect.Descriptor instead.
func (*UpdateT2Req) Descriptor() ([]byte, []int) {
	return file_t2_proto_rawDescGZIP(), []int{2}
}

type UpdateT2Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateT2Rsp) Reset() {
	*x = UpdateT2Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_t2_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateT2Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateT2Rsp) ProtoMessage() {}

func (x *UpdateT2Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_t2_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateT2Rsp.ProtoReflect.Descriptor instead.
func (*UpdateT2Rsp) Descriptor() ([]byte, []int) {
	return file_t2_proto_rawDescGZIP(), []int{3}
}

type DeleteT2Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteT2Req) Reset() {
	*x = DeleteT2Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_t2_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteT2Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteT2Req) ProtoMessage() {}

func (x *DeleteT2Req) ProtoReflect() protoreflect.Message {
	mi := &file_t2_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteT2Req.ProtoReflect.Descriptor instead.
func (*DeleteT2Req) Descriptor() ([]byte, []int) {
	return file_t2_proto_rawDescGZIP(), []int{4}
}

type DeleteT2Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteT2Rsp) Reset() {
	*x = DeleteT2Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_t2_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteT2Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteT2Rsp) ProtoMessage() {}

func (x *DeleteT2Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_t2_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteT2Rsp.ProtoReflect.Descriptor instead.
func (*DeleteT2Rsp) Descriptor() ([]byte, []int) {
	return file_t2_proto_rawDescGZIP(), []int{5}
}

type GetT2Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetT2Req) Reset() {
	*x = GetT2Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_t2_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetT2Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetT2Req) ProtoMessage() {}

func (x *GetT2Req) ProtoReflect() protoreflect.Message {
	mi := &file_t2_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetT2Req.ProtoReflect.Descriptor instead.
func (*GetT2Req) Descriptor() ([]byte, []int) {
	return file_t2_proto_rawDescGZIP(), []int{6}
}

type GetT2Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetT2Rsp) Reset() {
	*x = GetT2Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_t2_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetT2Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetT2Rsp) ProtoMessage() {}

func (x *GetT2Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_t2_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetT2Rsp.ProtoReflect.Descriptor instead.
func (*GetT2Rsp) Descriptor() ([]byte, []int) {
	return file_t2_proto_rawDescGZIP(), []int{7}
}

type ListT2Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListT2Req) Reset() {
	*x = ListT2Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_t2_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListT2Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListT2Req) ProtoMessage() {}

func (x *ListT2Req) ProtoReflect() protoreflect.Message {
	mi := &file_t2_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListT2Req.ProtoReflect.Descriptor instead.
func (*ListT2Req) Descriptor() ([]byte, []int) {
	return file_t2_proto_rawDescGZIP(), []int{8}
}

type ListT2Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListT2Rsp) Reset() {
	*x = ListT2Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_t2_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListT2Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListT2Rsp) ProtoMessage() {}

func (x *ListT2Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_t2_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListT2Rsp.ProtoReflect.Descriptor instead.
func (*ListT2Rsp) Descriptor() ([]byte, []int) {
	return file_t2_proto_rawDescGZIP(), []int{9}
}

var File_t2_proto protoreflect.FileDescriptor

var file_t2_proto_rawDesc = []byte{
	0x0a, 0x08, 0x74, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x74, 0x32, 0x22, 0x0d,
	0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x32, 0x52, 0x65, 0x71, 0x22, 0x0d, 0x0a,
	0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x32, 0x52, 0x73, 0x70, 0x22, 0x0d, 0x0a, 0x0b,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x32, 0x52, 0x65, 0x71, 0x22, 0x0d, 0x0a, 0x0b, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x32, 0x52, 0x73, 0x70, 0x22, 0x0d, 0x0a, 0x0b, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x54, 0x32, 0x52, 0x65, 0x71, 0x22, 0x0d, 0x0a, 0x0b, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x54, 0x32, 0x52, 0x73, 0x70, 0x22, 0x0a, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x54,
	0x32, 0x52, 0x65, 0x71, 0x22, 0x0a, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x54, 0x32, 0x52, 0x73, 0x70,
	0x22, 0x0b, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x32, 0x52, 0x65, 0x71, 0x22, 0x0b, 0x0a,
	0x09, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x32, 0x52, 0x73, 0x70, 0x32, 0xdb, 0x01, 0x0a, 0x02, 0x54,
	0x32, 0x12, 0x2c, 0x0a, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x32, 0x12, 0x0f, 0x2e,
	0x74, 0x32, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x32, 0x52, 0x65, 0x71, 0x1a, 0x0f,
	0x2e, 0x74, 0x32, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x32, 0x52, 0x73, 0x70, 0x12,
	0x2c, 0x0a, 0x08, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x32, 0x12, 0x0f, 0x2e, 0x74, 0x32,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x32, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x74,
	0x32, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x32, 0x52, 0x73, 0x70, 0x12, 0x2c, 0x0a,
	0x08, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x32, 0x12, 0x0f, 0x2e, 0x74, 0x32, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x32, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x74, 0x32, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x32, 0x52, 0x73, 0x70, 0x12, 0x23, 0x0a, 0x05, 0x47,
	0x65, 0x74, 0x54, 0x32, 0x12, 0x0c, 0x2e, 0x74, 0x32, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x32, 0x52,
	0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x74, 0x32, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x32, 0x52, 0x73, 0x70,
	0x12, 0x26, 0x0a, 0x06, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x32, 0x12, 0x0d, 0x2e, 0x74, 0x32, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x54, 0x32, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x74, 0x32, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x54, 0x32, 0x52, 0x73, 0x70, 0x42, 0x23, 0x0a, 0x02, 0x74, 0x32, 0x50, 0x01,
	0x5a, 0x1b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x65, 0x6e,
	0x67, 0x6c, 0x65, 0x6e, 0x67, 0x2f, 0x64, 0x64, 0x64, 0x64, 0x2f, 0x74, 0x32, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_t2_proto_rawDescOnce sync.Once
	file_t2_proto_rawDescData = file_t2_proto_rawDesc
)

func file_t2_proto_rawDescGZIP() []byte {
	file_t2_proto_rawDescOnce.Do(func() {
		file_t2_proto_rawDescData = protoimpl.X.CompressGZIP(file_t2_proto_rawDescData)
	})
	return file_t2_proto_rawDescData
}

var file_t2_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_t2_proto_goTypes = []interface{}{
	(*CreateT2Req)(nil), // 0: t2.CreateT2Req
	(*CreateT2Rsp)(nil), // 1: t2.CreateT2Rsp
	(*UpdateT2Req)(nil), // 2: t2.UpdateT2Req
	(*UpdateT2Rsp)(nil), // 3: t2.UpdateT2Rsp
	(*DeleteT2Req)(nil), // 4: t2.DeleteT2Req
	(*DeleteT2Rsp)(nil), // 5: t2.DeleteT2Rsp
	(*GetT2Req)(nil),    // 6: t2.GetT2Req
	(*GetT2Rsp)(nil),    // 7: t2.GetT2Rsp
	(*ListT2Req)(nil),   // 8: t2.ListT2Req
	(*ListT2Rsp)(nil),   // 9: t2.ListT2Rsp
}
var file_t2_proto_depIdxs = []int32{
	0, // 0: t2.T2.CreateT2:input_type -> t2.CreateT2Req
	2, // 1: t2.T2.UpdateT2:input_type -> t2.UpdateT2Req
	4, // 2: t2.T2.DeleteT2:input_type -> t2.DeleteT2Req
	6, // 3: t2.T2.GetT2:input_type -> t2.GetT2Req
	8, // 4: t2.T2.ListT2:input_type -> t2.ListT2Req
	1, // 5: t2.T2.CreateT2:output_type -> t2.CreateT2Rsp
	3, // 6: t2.T2.UpdateT2:output_type -> t2.UpdateT2Rsp
	5, // 7: t2.T2.DeleteT2:output_type -> t2.DeleteT2Rsp
	7, // 8: t2.T2.GetT2:output_type -> t2.GetT2Rsp
	9, // 9: t2.T2.ListT2:output_type -> t2.ListT2Rsp
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_t2_proto_init() }
func file_t2_proto_init() {
	if File_t2_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_t2_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateT2Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_t2_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateT2Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_t2_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateT2Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_t2_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateT2Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_t2_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteT2Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_t2_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteT2Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_t2_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetT2Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_t2_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetT2Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_t2_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListT2Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_t2_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListT2Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_t2_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_t2_proto_goTypes,
		DependencyIndexes: file_t2_proto_depIdxs,
		MessageInfos:      file_t2_proto_msgTypes,
	}.Build()
	File_t2_proto = out.File
	file_t2_proto_rawDesc = nil
	file_t2_proto_goTypes = nil
	file_t2_proto_depIdxs = nil
}
